#!/bin/bash
[ -z "$1" ] && echo "Usage: $0 window [command]" && exit 1
#xdotool search --onlyvisible $1 windowraise windowfocus || $1 &
[ -n "$2" ] && command=$2 || command=$1
xdotool search --onlyvisible $1
if [ $? -ne 0 ]; then
$command &
else
windows=$(xdotool search --onlyvisible $1)
for w in $windows; do
xdotool windowfocus $w windowraise $w
done
fi


